server:
  port: 8888
logging:
  path: logs
  file: mylog13Charpter.log
spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?useSSL=false&serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
